import { useEffect, useState } from "react";
import "./App.css";

type Disposition = "Admit" | "Observe" | "Discharge" | "Unknown";

type StructuredResult = {
  chiefComplaint: string;
  hpiSummary: string;
  keyFindings: string[];
  suspectedConditions: string[];
  dispositionRecommendation: Disposition;
  uncertainties: string[];
  revisedHpi: string;
  evidence?: {
    demographics?: string;
    symptoms: string[];
    exam: string[];
    labs: string[];
    treatments: string[];
    dispositionSignals: string[];
  };
  generatedBy: string;
};

type SavedCaseListItem = {
  id: string;
  title: string;
  is_edited: boolean;
  created_at: string;
  updated_at: string;
};

type SavedCase = {
  id: string;
  title: string;
  original_note: string;
  generated_result: StructuredResult;
  edited_result: StructuredResult | null;
  is_edited: boolean;
  created_at: string;
  updated_at: string;
};

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:4000";

function joinLines(values: string[] | undefined): string {
  return values?.join("\n") || "";
}

function splitLines(value: string): string[] {
  return value
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

function App() {
  const [originalNote, setOriginalNote] = useState("");
  const [result, setResult] = useState<StructuredResult | null>(null);
  const [machineResult, setMachineResult] = useState<StructuredResult | null>(null);
  const [title, setTitle] = useState("");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(false);
  const [savedCases, setSavedCases] = useState<SavedCaseListItem[]>([]);
  const [selectedCaseId, setSelectedCaseId] = useState<string | null>(null);

  const isEdited =
    machineResult && result
      ? JSON.stringify(machineResult) !== JSON.stringify(result)
      : false;

  async function loadSavedCases() {
    try {
      const response = await fetch(`${API_BASE_URL}/api/cases`);
      if (!response.ok) throw new Error("Failed to load saved cases.");
      const data = await response.json();
      setSavedCases(data);
    } catch {
      setStatus("Could not load saved cases.");
    }
  }

  useEffect(() => {
    loadSavedCases();
  }, []);

  async function generateResult() {
    if (!originalNote.trim()) {
      setStatus("Paste a clinical note first.");
      return;
    }

    setLoading(true);
    setStatus("Generating structured result...");

    try {
      const response = await fetch(`${API_BASE_URL}/api/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          originalNote
        })
      });

      if (!response.ok) {
        throw new Error("Generate request failed.");
      }

      const data = await response.json();
      setTitle(data.title);
      setMachineResult(data.result);
      setResult(data.result);
      setSelectedCaseId(null);
      setStatus("Generated by rule-based engine. Review and edit before saving.");
    } catch {
      setStatus("Failed to generate result. Make sure the backend is running on port 4000.");
    } finally {
      setLoading(false);
    }
  }

  async function saveNewCase() {
    if (!result || !machineResult) {
      setStatus("Generate a result before saving.");
      return;
    }

    setLoading(true);
    setStatus("Saving case...");

    try {
      const createResponse = await fetch(`${API_BASE_URL}/api/cases`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          originalNote,
          generatedResult: machineResult,
          title: title || result.chiefComplaint || "Clinical case"
        })
      });

      if (!createResponse.ok) {
        throw new Error("Failed to create case.");
      }

      const savedCase = await createResponse.json();

      if (isEdited) {
        const updateResponse = await fetch(`${API_BASE_URL}/api/cases/${savedCase.id}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            editedResult: result
          })
        });

        if (!updateResponse.ok) {
          throw new Error("Failed to save edits.");
        }
      }

      setSelectedCaseId(savedCase.id);
      await loadSavedCases();
      setStatus(isEdited ? "Saved case with user edits." : "Saved machine-generated case.");
    } catch {
      setStatus("Failed to save case.");
    } finally {
      setLoading(false);
    }
  }

  async function saveEdits() {
    if (!selectedCaseId || !result) {
      setStatus("Open or save a case before saving edits.");
      return;
    }

    setLoading(true);
    setStatus("Saving edits...");

    try {
      const response = await fetch(`${API_BASE_URL}/api/cases/${selectedCaseId}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          editedResult: result
        })
      });

      if (!response.ok) {
        throw new Error("Failed to update case.");
      }

      await loadSavedCases();
      setStatus("Saved user-edited content.");
    } catch {
      setStatus("Failed to save edits.");
    } finally {
      setLoading(false);
    }
  }

  async function openSavedCase(id: string) {
    setLoading(true);
    setStatus("Opening saved case...");

    try {
      const response = await fetch(`${API_BASE_URL}/api/cases/${id}`);
      if (!response.ok) {
        throw new Error("Failed to open saved case.");
      }

      const data: SavedCase = await response.json();
      const currentResult = data.edited_result || data.generated_result;

      setSelectedCaseId(data.id);
      setTitle(data.title);
      setOriginalNote(data.original_note);
      setMachineResult(data.generated_result);
      setResult(currentResult);
      setStatus(data.is_edited ? "Opened saved case with user edits." : "Opened saved machine-generated case.");
    } catch {
      setStatus("Failed to open saved case.");
    } finally {
      setLoading(false);
    }
  }

  function updateResult<K extends keyof StructuredResult>(
    key: K,
    value: StructuredResult[K]
  ) {
    if (!result) return;
    setResult({
      ...result,
      [key]: value
    });
  }

  return (
    <main className="page">
      <header className="hero">
        <h1>Clinical Note Structuring Tool</h1>
        <p>
          Paste an unstructured clinical note, generate structured fields and a revised HPI,
          then review, edit, save, and reopen the result.
        </p>
      </header>

      <section className="appLayout">
        <aside className="sidebar">
          <section className="card">
            <div className="sectionHeader single">
              <div>
                <h2>Saved Cases</h2>
                <p className="muted">Previously saved generated or edited notes.</p>
              </div>
            </div>

            {savedCases.length === 0 ? (
              <p className="emptyState">No saved cases yet.</p>
            ) : (
              <div className="caseList">
                {savedCases.map((savedCase) => (
                  <button
                    key={savedCase.id}
                    className={
                      selectedCaseId === savedCase.id
                        ? "caseButton active"
                        : "caseButton"
                    }
                    onClick={() => openSavedCase(savedCase.id)}
                    disabled={loading}
                  >
                    <span className="caseTitle">{savedCase.title}</span>
                    <span className="caseMeta">
                      {savedCase.is_edited ? "User edited" : "Machine generated"}
                    </span>
                  </button>
                ))}
              </div>
            )}
          </section>
        </aside>

        <section className="mainContent">
          <section className="card">
            <div className="sectionHeader">
              <div>
                <h2>1. Original Clinical Note</h2>
                <p className="muted">
                  Paste an ER note, H&amp;P note, or combined clinical text.
                </p>
              </div>

              <button onClick={generateResult} disabled={loading}>
                {loading ? "Working..." : "Generate"}
              </button>
            </div>

            <textarea
              className="noteInput"
              value={originalNote}
              onChange={(event) => setOriginalNote(event.target.value)}
              placeholder="Paste clinical note here..."
            />
          </section>

          {result && (
            <section className="card">
              <div className="sectionHeader">
                <div>
                  <h2>2. Structured Result</h2>
                  <p className="muted">
                    {isEdited ? "User-edited content" : "Machine-generated content"}
                  </p>
                </div>

                <div className="actionGroup">
                  {title && <span className="pill">{title}</span>}
                  <button onClick={saveNewCase} disabled={loading}>
                    Save New Case
                  </button>
                  <button onClick={saveEdits} disabled={loading || !selectedCaseId}>
                    Save Edits
                  </button>
                </div>
              </div>

              <label>
                Chief Complaint
                <input
                  value={result.chiefComplaint}
                  onChange={(event) =>
                    updateResult("chiefComplaint", event.target.value)
                  }
                />
              </label>

              <label>
                HPI Summary
                <textarea
                  value={result.hpiSummary}
                  onChange={(event) =>
                    updateResult("hpiSummary", event.target.value)
                  }
                />
              </label>

              <label>
                Key Findings
                <textarea
                  value={joinLines(result.keyFindings)}
                  onChange={(event) =>
                    updateResult("keyFindings", splitLines(event.target.value))
                  }
                />
              </label>

              <label>
                Suspected Condition(s)
                <textarea
                  value={joinLines(result.suspectedConditions)}
                  onChange={(event) =>
                    updateResult(
                      "suspectedConditions",
                      splitLines(event.target.value)
                    )
                  }
                />
              </label>

              <label>
                Disposition Recommendation
                <select
                  value={result.dispositionRecommendation}
                  onChange={(event) =>
                    updateResult(
                      "dispositionRecommendation",
                      event.target.value as Disposition
                    )
                  }
                >
                  <option value="Admit">Admit</option>
                  <option value="Observe">Observe</option>
                  <option value="Discharge">Discharge</option>
                  <option value="Unknown">Unknown</option>
                </select>
              </label>

              <label>
                Uncertainties / Missing Information
                <textarea
                  value={joinLines(result.uncertainties)}
                  onChange={(event) =>
                    updateResult("uncertainties", splitLines(event.target.value))
                  }
                />
              </label>

              <label>
                Revised HPI
                <textarea
                  className="revisedHpi"
                  value={result.revisedHpi}
                  onChange={(event) =>
                    updateResult("revisedHpi", event.target.value)
                  }
                />
              </label>

              {result.evidence && (
                <details className="evidenceBox">
                  <summary>Extracted Evidence</summary>
                  <pre>{JSON.stringify(result.evidence, null, 2)}</pre>
                </details>
              )}
            </section>
          )}

          {status && <div className="status">{status}</div>}
        </section>
      </section>
    </main>
  );
}

export default App;